server {
    listen 80;
    server_name localhost;
    absolute_redirect off;

    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    location = / {
        return 302 /vpc/;
    }

    location = /auth {
        return 308 /auth/;
    }

    location = /vpc {
        return 308 /vpc/;
    }

    location = /vm {
        return 308 /vm/;
    }

    location = /ctr {
        return 308 /ctr/;
    }

    location = /bs {
        return 308 /bs/;
    }

    location = /vpn {
        return 308 /vpn/;
    }

    location /auth/ {
        proxy_pass http://host.docker.internal:3005/auth/;
    }

    location /vpc/ {
        proxy_pass http://host.docker.internal:3000/vpc/;
    }

    location /vm/ {
        proxy_pass http://host.docker.internal:3001/vm/;
    }

    location /ctr/ {
        proxy_pass http://host.docker.internal:3002/ctr/;
    }

    location /bs/ {
        proxy_pass http://host.docker.internal:3003/bs/;
    }

    location /vpn/ {
        proxy_pass http://host.docker.internal:3004/vpn/;
    }
}
